version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - run: mkdir -p docs/_build/html
      - run: wget http://sunpy.org/index.html -O docs/_build/html/index.html
      
      
      - run: mkdir -p gen
      - run: wget https://9315-24998719-gh.circle-artifacts.com/0/root/project/scripts/gen/index.html -O gen/index.html
      
      
      - run: mkdir -p client-server
      - run: wget https://9316-24998719-gh.circle-artifacts.com/0/root/project/api/client-server/index.html -O client-server/index.html

      - store_artifacts:
          path: docs/_build/html
          path: gen/index.html
          path: client-server/index.html

      - run:
          name: "Built documentation is available at:"
          command: DOCS_URL="${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/docs/_build/html/index.html"; echo $DOCS_URL


notify:
  webhooks:
    - url: https://giles.cadair.dev/circleci
